### PR TITLE
Updated README with a short 'About' section

### PR DESCRIPTION
**Pull request by aravindharinair**
While @shashank-sharma filled out the details (awesome, btw), the single line on top ("This is a placeholder...") felt lonely. So, I filled it up with a short 'About' section regarding the Org...

What do you say?

### CODE REVIEW

**Review by irshad2809 — APPROVED** [review]
Great work there

**Comment by aravindharinair** [comment]
thanks! :smile:

**Review by kundanvishen — APPROVED** [review]
Thanks!

**Comment by shashank-sharma** [comment]
@aravindharinair Great work :D, just to inform make sure that next time you squash all your commits into 1 commit as later in future it will look messy.

**Comment by aravindharinair** [comment]
@shashank-sharma thanks. :)
Will remember to squash in the future...

**Pull request merged**
