### PR TITLE
Initiated website 

### PR DESCRIPTION
**Pull request by abdus**
Hey, initiated the website building process. Modify it. Let's rock. xD

### CODE REVIEW

**Comment by abdus** [comment]
screenshot from 2018-02-17 23-25-16
here is a screenshot. I used 'ace devs' as a logo placeholder.

**Comment by kundanvishen** [comment]
@thisisabdus that is some great work! But I won't be merging this to master. I know it's hard work.
But whatever merged to master goes straight live.
But again, awesome work. Let's improve it more and resolve few issues and then merge it?

**Comment by aravindharinair** [comment]
Looks ok, nice effort.
But the minimalist touch is better, don't you think?
Like Google's Material Design, etc...

**Comment by abdus** [comment]
No worries. I will close this PR. Should I compare it with stage branch or redesign it?

**Comment by aravindharinair** [comment]
Redesign it! :D
Make it better, more polished...

**Pull request closed without merging**
