### PR TITLE
Upload landing page files

### PR DESCRIPTION
**Pull request by aravindharinair**
Created landing page and set to Under Construction status.
Basic setup. Built during class interval. Reused a stylesheet from another project.

Basically, just a placeholder.

### CODE REVIEW

**Comment by aravindharinair** [comment]
Leaving it here for anyone to verify and such. If no one has objections, I will be merging these after 5pm IST...

**Review by kundanvishen — APPROVED** [review]
Great Work!

**Comment by kundanvishen** [comment]
@aravindharinair 
Merged buddy, but the background page is just too big in size (3.4 MB)!

I'll create a pull request and merge after removing the image.

**Comment by aravindharinair** [comment]
I know the size we a bit high... Didn't have much time, so just pulled the smallest clean image I could find on my system... :'D

**Pull request merged**
